language: java

jdk:
  - openjdk8
script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  && mvn cobertura:cobertura"

notifications:
  email: true

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
  - bash <(curl -s https://codecov.io/bash)