version: '3.8'
services:
  server:
    image: jpom_server:${JPOM_VERSION}
    build:
      dockerfile: Dockerfile.server
      context: .
      args:
        JPOM_VERSION: ${JPOM_VERSION}
    volumes:
      - jpom-server:/usr/local/jpom-server
    ports:
      - "2122:2122"
  agent:
    image: jpom_agent:${JPOM_VERSION}
    build:
      dockerfile: Dockerfile.agent
      context: .
      args:
        JPOM_VERSION: ${JPOM_VERSION}
    volumes:
      - jpom-agent:/usr/local/jpom-agent
    ports:
      - "2123:2123"
volumes:
  jpom-agent:
  jpom-server:
