#\u7A0B\u5E8F\u7AEF\u53E3\u53F7
server:
  port: 2122
spring:
  application:
    name: jpom
  profiles:
    active: dev
  #velocity \u6A21\u677F\u6587\u4EF6\u914D\u7F6E
  velocity:
    charset:  UTF-8
    content-type: text/html
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    enabled: true
    resource-loader-path: classpath:/vm/
    suffix: .vm
banner:
  msg: jpom 管理系统启动中
#boot online \u914D\u7F6E
jpom:
  path: /jpom/
# \u9759\u6001\u8D44\u6E90
interceptor:
  resourceHandler: /static/**
  resourceLocation: classpath:/static/
tomcat:
  sessionTimeOut: 18000
preload:
  packageName: cn.jiangzeyin.system.init