#运行端口号
server:
  port: 2122
  servlet:
    session:
      cookie:
        name: JPOMID-SERVER
      timeout: 1H
spring:
  application:
    name: jpomServer
  profiles:
    active: dev
  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-request-size: 2GB
      max-file-size: 1GB
#thymeleaf end
banner:
  msg: Jpom-Server 管理系统启动中
# 静态资源配置
interceptor:
  resourceHandler: /static/**,/favicon.ico
  resourceLocation: classpath:/static/,classpath:/static/favicon.ico
# 启动完成自动初始化指定包
preload:
  packageName: io.jpom.system.init
# 强制去掉空格
request:
  trimAll: true
  parameterXss: false