#运行端口号
server:
  port: 2122
spring:
  application:
    name: jpomServer
  profiles:
    active: dev
  velocity:
    charset:  UTF-8
    content-type: text/html
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    enabled: true
    resource-loader-path: classpath:/vm/
    suffix: .vm
  #thymeleaf start
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/vm/
#thymeleaf end
banner:
  msg: Jpom-Server 管理系统启动中
# 静态资源配置
interceptor:
  resourceHandler: /static/**
  resourceLocation: classpath:/static/
# session 超时时间
tomcat:
  sessionTimeOut: 3600
  sessionCookieName: JPOMID-SERVER
# 启动完成自动初始化指定包
preload:
  packageName: cn.keepbx.jpom.system.init
# 强制去掉空格
request:
  trimAll: true