jpom:
  # jpom 数据存储路径, 如果调试模式运行默认路径为【/jpom/】,安装运行默认为jar包文件的父级
  path:
  authorize:
    # agent 端管理账号，必填。
    agentName: jpomAgent
    # agent 端管理密码，非必填，如果为空Jpom 会自动生成一串随机字符串当密码
    agentPwd:
  agent:
    # 设置插件端id，配置自动注册服务端需要
    id:
    # 当前节点插件端可以访问的url ,如果不设置将使用http://+本地IP+端口
    url:
  server:
    # 设置服务端的url
    url:
    # 服务器接口请求token
    token:
whitelistDirectory:
  # 白名单目录是否验证包含关系
  checkStartsWith: true
log:
  # 自动备份控制台日志，防止日志文件过大，目前暂只支持linux 不停服备份
  autoBackConsoleCron: 0 0/10 * * * ?
  # 当文件多大时自动备份
  autoBackSize: 50MB
  # 保存天数 配置错误或者没有，默认是7天
  saveDays: 7
  # 日志文件的编码格式，如果没有指定就自动识别，自动识别可能出现不准确的情况
  fileCharset:
  # 查看日志时初始读取最后多少行（默认10，0不读取）
  intiReadLine: 10
consoleLog:
  # 是否记录接口请求日志
  reqXss: true
  # 是否记录接口响应日志
  reqResponse: true
project:
  # 是否禁用 使用jmx获取项目状态
  disableVirtualMachine: false
  # 停止项目等待的时长 单位秒
  stopWaitTime: 10
