jpom:
  # jpom 数据存储路径, 如果调试模式运行默认路径为【/jpom/】,安装运行默认为jar包文件的父级
  path:
  authorize:
    # api接口请求token 长度要求大于等于6位，字母数字符号组合
    token:
    #登录token失效时间(单位：小时),默认为24
    expired: 24
    #登录token失效后自动续签时间（单位：分钟），默认为60，不自动续签
    renewal: 60
    # jwt 签名(加密)的key 长度建议控制到 16位
    key:
user:
  # 最多能创建多少个用户
  maxCount: 10
  # 用户连续登录失败次数，超过此数将被限制登录
  alwaysLoginError: 5
  # 当ip连续登录失败，锁定对应IP时长，单位毫秒
  ipErrorLockTime: 60*60*5*1000
consoleLog:
  # 是否记录接口请求日志
  reqXss: true
  # 是否记录接口响应日志
  reqResponse: true
log:
  # 日志文件的编码格式，如果没有指定就自动识别，自动识别可能出现不准确的情况
  fileCharset:
  # 查看日志时初始读取最后多少行（默认10，0不读取）
  intiReadLine: 10
db:
  # 日志存储条数，将自动清理旧数据,配置小于等于零则不清理
  logStorageCount: 100000
  # 数据库账号
  userName:
  # 数据库密码
  userPwd:
# 构建相关配置
build:
  # 最多保存多少份历史记录
  maxHistoryCount: 1000
  # 单个最多保存多少份历史记录
  itemMaxHistoryCount: 50
ssh:
  # ssh 执行命令的 默认加载的环境变量
  initEnv: source /etc/profile && source ~/.bash_profile && source ~/.bashrc
