name: codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        run: bash <(curl -s https://codecov.io/bash)